---
- name: Base Configuration for Routers
  hosts: routers
  gather_facts: no



  tasks:
  - name: test Connection
    cisco.ios.ios_config:
      lines:
        - interface Loopback0
        - description Configured by Ansible
        - ip address 69.69.69.69 255.255.255.255

